environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHONPATH;%PATH%
  - set PYTHONPATH=%PYTHONPATH%;%PYTHON%\\Lib;%PYTHON%\\Scripts
  - "python -m pip install protobuf"
  - "python -m pip install pyopenssl"
  - "python setup.py bdist_msi"
  - "dist\\drozer-2.4.3.win-amd64.msi /quiet"

deploy:
  provider: GitHub
  auth_token:  
    secure: gCPf8e7yG7XU3qSFRoRhhf4KT4LQAyluvcshLyWWZSudPE868fDq8Cs/gMNnTfiR
  artifact: dist/*
  draft: false
  description: ''
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

artifacts:
  - path: dist\*.msi
    name: Drozer Installer


build: off

# test_script:

# after_test:

# artifacts:
#   - path: dist\*

#on_success:
