environment:
    
  matrix:
    - PYTHON: "C:\\Python27"
      JAVA_HOME: "C:\\Program Files (x86)\\Java\\jdk1.7.0"
    - PYTHON: "C:\\Python27-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.7.0"

init:
  - ECHO %PYTHON% %JAVA_HOME%

install:
  - set PATH=%PATH:C:\Program Files\Java\jdk1.8.0\bin;=%
  - set PYTHONPATH=%PYTHONPATH%;%PYTHON%\\Lib;%PYTHON%\\Scripts
  - set PATH=%PATH%;%JAVA_HOME%\bin
  - "python -m pip install protobuf"
  - "python -m pip install pyopenssl"
  - "python setup.py bdist_msi"

artifacts:
  - path: dist\*.msi
    name: DrozerInstaller

deploy:
  provider: GitHub
  auth_token:  
    secure: gCPf8e7yG7XU3qSFRoRhhf4KT4LQAyluvcshLyWWZSudPE868fDq8Cs/gMNnTfiR
  artifact: DrozerInstaller
  draft: false
  description: ''
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

build: off

# test_script:

# after_test:

# artifacts:
#   - path: dist\*

#on_success:
